//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machine.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 State &apos;{0}&apos; cannot have transition &apos;{1}&apos; to state &apos;{2}&apos; because it&apos;s one of ancestors of state &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AncestorCannotHaveTransitionToDescendant {
            get {
                return ResourceManager.GetString("AncestorCannotHaveTransitionToDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final state &apos;{0}&apos; must not have any child states. 的本地化字符串。
        /// </summary>
        internal static string FinalStateCannotHaveChildState {
            get {
                return ResourceManager.GetString("FinalStateCannotHaveChildState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final state &apos;{0}&apos; must not have an entry action. 的本地化字符串。
        /// </summary>
        internal static string FinalStateCannotHaveEntry {
            get {
                return ResourceManager.GetString("FinalStateCannotHaveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final state &apos;{0}&apos; must not have an exit action. 的本地化字符串。
        /// </summary>
        internal static string FinalStateCannotHaveExit {
            get {
                return ResourceManager.GetString("FinalStateCannotHaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final state &apos;{0}&apos; must not have any outgoing transitions. 的本地化字符串。
        /// </summary>
        internal static string FinalStateCannotHaveTransition {
            get {
                return ResourceManager.GetString("FinalStateCannotHaveTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final state &apos;{0}&apos; can only be on root level and should not be parented by state &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string FinalStateCanOnlyBeOnRootLevel {
            get {
                return ResourceManager.GetString("FinalStateCanOnlyBeOnRootLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial state &apos;{0}&apos; must not also be a final state. 的本地化字符串。
        /// </summary>
        internal static string InitialStateCannotBeFinalState {
            get {
                return ResourceManager.GetString("InitialStateCannotBeFinalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial state &apos;{0}&apos; must be a simple state. 的本地化字符串。
        /// </summary>
        internal static string InitialStateMustBeSimpleState {
            get {
                return ResourceManager.GetString("InitialStateMustBeSimpleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple state &apos;{0}&apos; has no inherited transition from its ancestors, thus it must have at least 1 transition. 的本地化字符串。
        /// </summary>
        internal static string SimpleStateWithoutInheritedTransitionMustHaveTransition {
            get {
                return ResourceManager.GetString("SimpleStateWithoutInheritedTransitionMustHaveTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State &apos;{0}&apos; must not be added to multiple parent states or added to the same parent state multiple times. 的本地化字符串。
        /// </summary>
        internal static string StateCannotHaveMultipleParents {
            get {
                return ResourceManager.GetString("StateCannotHaveMultipleParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StateMachine &apos;{0}&apos; must have an initial state. 的本地化字符串。
        /// </summary>
        internal static string StateMachineMustHaveInitialState {
            get {
                return ResourceManager.GetString("StateMachineMustHaveInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State &apos;{0}&apos; must belong to a composite state or the state machine. 的本地化字符串。
        /// </summary>
        internal static string StateNotBelongToAnyParent {
            get {
                return ResourceManager.GetString("StateNotBelongToAnyParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State &apos;{0}&apos; is not a simple state. So it cannot be target state of transition &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TargetStateMustBeSimpleState {
            get {
                return ResourceManager.GetString("TargetStateMustBeSimpleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of completed events in queue exceeds the max limit: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TooManyCompletedEvents {
            get {
                return ResourceManager.GetString("TooManyCompletedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition &apos;{0}&apos; cannot be added to state &apos;{1}&apos; because it has been added to state &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TransitionCannotBeAddedTwice {
            get {
                return ResourceManager.GetString("TransitionCannotBeAddedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;To&apos; property of transition &apos;{0}&apos; of state &apos;{1}&apos; must not be null. 的本地化字符串。
        /// </summary>
        internal static string TransitionTargetCannotBeNull {
            get {
                return ResourceManager.GetString("TransitionTargetCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger of transition &apos;{0}&apos; of state &apos;{1}&apos; cannot be null. 的本地化字符串。
        /// </summary>
        internal static string TriggerCannotBeNull {
            get {
                return ResourceManager.GetString("TriggerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition &apos;{0}&apos; of state &apos;{1}&apos; is an unconditional transition. It may not share the same trigger &apos;{2}&apos; with other transition(s). 的本地化字符串。
        /// </summary>
        internal static string UnconditionalTransitionShouldnotShareTriggersWithOthers {
            get {
                return ResourceManager.GetString("UnconditionalTransitionShouldnotShareTriggersWithOthers", resourceCulture);
            }
        }
    }
}
