//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine.Design {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machine.Design.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot construct line segment between point {0} and point {1}. 的本地化字符串。
        /// </summary>
        internal static string CannotConstructConnectionSegment {
            get {
                return ResourceManager.GetString("CannotConstructConnectionSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create link. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateLink {
            get {
                return ResourceManager.GetString("CannotCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create transition from a state to its descendant. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateTransitionFromAncestorToDescendant {
            get {
                return ResourceManager.GetString("CannotCreateTransitionFromAncestorToDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create transition to a composite state. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateTransitionToCompositeState {
            get {
                return ResourceManager.GetString("CannotCreateTransitionToCompositeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set a composite state as the initial state. 的本地化字符串。
        /// </summary>
        internal static string CannotSetCompositeStateAsInitialState {
            get {
                return ResourceManager.GetString("CannotSetCompositeStateAsInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set a final state as the initial state. 的本地化字符串。
        /// </summary>
        internal static string CannotSetFinalStateAsInitialState {
            get {
                return ResourceManager.GetString("CannotSetFinalStateAsInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear initial state 的本地化字符串。
        /// </summary>
        internal static string ClearInitialState {
            get {
                return ResourceManager.GetString("ClearInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a line to create a transition 的本地化字符串。
        /// </summary>
        internal static string ConnectionPointTooltip {
            get {
                return ResourceManager.GetString("ConnectionPointTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create transition 的本地化字符串。
        /// </summary>
        internal static string CreateTransition {
            get {
                return ResourceManager.GetString("CreateTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final 的本地化字符串。
        /// </summary>
        internal static string DefaultFinalStateDisplayName {
            get {
                return ResourceManager.GetString("DefaultFinalStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string DefaultStateDisplayName {
            get {
                return ResourceManager.GetString("DefaultStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition 的本地化字符串。
        /// </summary>
        internal static string DefaultTransitionDisplayName {
            get {
                return ResourceManager.GetString("DefaultTransitionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click to edit transition details 的本地化字符串。
        /// </summary>
        internal static string EditTransitionTooltip {
            get {
                return ResourceManager.GetString("EditTransitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow Designer 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Move 的本地化字符串。
        /// </summary>
        internal static string ItemMove {
            get {
                return ResourceManager.GetString("ItemMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move link 的本地化字符串。
        /// </summary>
        internal static string MoveLink {
            get {
                return ResourceManager.GetString("MoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize 的本地化字符串。
        /// </summary>
        internal static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set initial state 的本地化字符串。
        /// </summary>
        internal static string SetInitialState {
            get {
                return ResourceManager.GetString("SetInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a line to create a new transition that shares the same trigger 的本地化字符串。
        /// </summary>
        internal static string SharedTriggerToolTip {
            get {
                return ResourceManager.GetString("SharedTriggerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger:  的本地化字符串。
        /// </summary>
        internal static string TriggerNameToolTip {
            get {
                return ResourceManager.GetString("TriggerNameToolTip", resourceCulture);
            }
        }
    }
}
