//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine.Design {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machine.Design.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct line segment between point {0} and point {1}..
        /// </summary>
        internal static string CannotConstructConnectionSegment {
            get {
                return ResourceManager.GetString("CannotConstructConnectionSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create link..
        /// </summary>
        internal static string CannotCreateLink {
            get {
                return ResourceManager.GetString("CannotCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create transition from a state to its descendant..
        /// </summary>
        internal static string CannotCreateTransitionFromAncestorToDescendant {
            get {
                return ResourceManager.GetString("CannotCreateTransitionFromAncestorToDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create transition to a composite state..
        /// </summary>
        internal static string CannotCreateTransitionToCompositeState {
            get {
                return ResourceManager.GetString("CannotCreateTransitionToCompositeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a composite state as the initial state..
        /// </summary>
        internal static string CannotSetCompositeStateAsInitialState {
            get {
                return ResourceManager.GetString("CannotSetCompositeStateAsInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a final state as the initial state..
        /// </summary>
        internal static string CannotSetFinalStateAsInitialState {
            get {
                return ResourceManager.GetString("CannotSetFinalStateAsInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear initial state.
        /// </summary>
        internal static string ClearInitialState {
            get {
                return ResourceManager.GetString("ClearInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a line to create a transition.
        /// </summary>
        internal static string ConnectionPointTooltip {
            get {
                return ResourceManager.GetString("ConnectionPointTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create transition.
        /// </summary>
        internal static string CreateTransition {
            get {
                return ResourceManager.GetString("CreateTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string DefaultFinalStateDisplayName {
            get {
                return ResourceManager.GetString("DefaultFinalStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string DefaultStateDisplayName {
            get {
                return ResourceManager.GetString("DefaultStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition.
        /// </summary>
        internal static string DefaultTransitionDisplayName {
            get {
                return ResourceManager.GetString("DefaultTransitionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to edit transition details.
        /// </summary>
        internal static string EditTransitionTooltip {
            get {
                return ResourceManager.GetString("EditTransitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Designer.
        /// </summary>
        internal static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Move.
        /// </summary>
        internal static string ItemMove {
            get {
                return ResourceManager.GetString("ItemMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move link.
        /// </summary>
        internal static string MoveLink {
            get {
                return ResourceManager.GetString("MoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set initial state.
        /// </summary>
        internal static string SetInitialState {
            get {
                return ResourceManager.GetString("SetInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a line to create a new transition that shares the same trigger.
        /// </summary>
        internal static string SharedTriggerToolTip {
            get {
                return ResourceManager.GetString("SharedTriggerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger: .
        /// </summary>
        internal static string TriggerNameToolTip {
            get {
                return ResourceManager.GetString("TriggerNameToolTip", resourceCulture);
            }
        }
    }
}
